### ISSUE TITLE
Will web plugin support joining meeting as guest using meeting link

### ISSUE THREAD

**Issue by TheMohanraj** [OfficeDev/skype-web-sdk-samples#10]
I found android android sdk capable of joining meeting url (https://meet.company.in/user/ERUOER) as guest.
But I couldn't find that option in web sdk sample.

**Comment by srividhc** [comment]
https://msdn.microsoft.com/en-us/skype/websdk/anonymousmeetingjoin
Please refer to MSDN for the details of what is available in each SDK.

Also, please post your questions to Stackoverflow tag: SkypeDeveloper going forward.
