### ISSUE TITLE
Leaving Conversation Feature Disabled

### ISSUE THREAD

**Issue by MikeDev2016** [OfficeDev/skype-web-sdk-samples#12]
Hi,

When attempting to leave a conversation via _conversation.leave()_ or attempting to stop an IM modality via _conversation.chatService.stop()_ nothing happens.

When examining the conversation _BaseModel_, via for example _skypeWebApp.conversationsManager.conversations.get()_ it can be seen that both methods _leave()_ and _chatService.stop()_ have the enabled property set to _false_.

Could we be provided with an explanation as to why this is the case and/or if this feature is or is to be in development?

Thank you in advance.

**Comment by sidharthv** [comment]
chatService.stop is enabled only if chatService is in a connected or connecting state. If your conversation was left inactive for a certain period of time (probably around 10 minutes for a p2p conversation but you should not rely on this time as it can change) then the conversation gets disconnected automatically and so chatService.stop will get disabled, and chatService.start will get enabled. This is probably what you encountered.

**Comment by MikeDev2016** [comment]
You're absolutely correct. When the chat is in fact in a connected state, both _chatService.stop()_ and _conversation.leave()_ are enabled. Thank you for the clarification.
