### ISSUE TITLE
Issue with Online samples

### ISSUE THREAD

**Issue by peili** [OfficeDev/skype-web-sdk-samples#3]
I followed the steps provided in the [documentation](https://msdn.microsoft.com/en-us/library/office/mt622687%28v=office.16%29.aspx)

There you can find a "snippet to create an authorization header". However this repository uncomments the code in the [sign-in.js](https://github.com/OfficeDev/skype-web-sdk-samples/blob/master/SkypeWebSDKOnlineSample/UI/samples/scripts/sign-in.js) to use the authorization header. Also when calling signIn() a 401 is returned for "https://webdir1a.online.lync.com/Autodiscover/AutodiscoverService.svc/root/oauth/user" "401 - Unauthorized: Access is denied due to invalid credentials"

**Comment by mwambler** [comment]
Make sure you update client_id value everywhere (3 hard-coded references, sign-in.js, index.hml).  After updating the application logged in without issue.
