### ISSUE TITLE
How can I get all contacts from Office 365?

### ISSUE THREAD

**Issue by pmironov** [OfficeDev/skype-web-sdk-samples#32]
Hi, is there any way I can get all users from Office 365, not only ones that were added to my contacts list. For example, I have 10 users in my Office 365, and added two of them in my contacts list in Skype. When I call `personsAndGroupsManager.all.persons.get()` I receive only my two contacts. 
Same happens when I get all my groups `personsAndGroupsManager.all.groups.get()` and retrieve contacts from each of them `group.persons.get()`. Only two contacts that were added previously are retrieved.

Is there a way to get all my 10 contacts? I saw OWA Skype app able to do that as it shows all the contacts from Office365 on Contacts pane.

**Comment by stewartadam** [comment]
Please see details here: [All](https://msdn.microsoft.com/en-us/skype/websdk/docs/ptcontactsall) contacts group and [Search](https://msdn.microsoft.com/en-us/skype/websdk/docs/ptcontactssearch).

For more detailed O365 user information, you can also use [Microsoft Graph](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/users).

If this has resolved your issue please mark the issue as closed. Thanks!
