### ISSUE TITLE
Can not load the SDK error.

### ISSUE THREAD

**Issue by zhangsichu** [OfficeDev/skype-web-sdk-samples#7]
https://latest-swx.cdn.skype.com/jLync/master_0.4.155/sdk.js
can not load this javascript file.
page pop up the alert window:

"Can not load the SDK"

**Comment by zhangsichu** [comment]
![123](https://cloud.githubusercontent.com/assets/995849/15174609/ffd4160e-1794-11e6-9ef5-2864dcf277b0.png)

**Comment by sivijaya** [comment]
Can you share a Fiddler trace? Also, there should be an error in the console. What does that say?

**Comment by zhangsichu** [comment]
fiddler load the script file: https://latest-swx.cdn.skype.com/jLync/master_0.4.155/sdk.js
time out.

**Comment by sivijaya** [comment]
What does the error in the console say? Also, are you able to download that sdk.js file through the browser?
Please share a Fiddler trace for further investigation.

**Comment by zhangsichu** [comment]
console say: can not load the sdk.js file.
i can not download that sdk.js through browser.

**Comment by sivijaya** [comment]
Is the url of sdk.js not resolvable to you through the browser? Can you tell me what geographic location you are trying it from? Maybe the CDN hosting the file is not accessible from your location.

**Comment by zhangsichu** [comment]
from the china mainland, now it works. the url is latest-swx.cdn.skype.com
i just ping this address:
Pinging cs3.wpc.v0cdn.net [68.232.45.201] with 32 bytes of data:
Reply from 68.232.45.201: bytes=32 time=167ms TTL=128
Reply from 68.232.45.201: bytes=32 time=165ms TTL=128
Reply from 68.232.45.201: bytes=32 time=166ms TTL=128

**Comment by zhangsichu** [comment]
the cdn is not stable, sometimes time out.
